# Generated by Django 5.1.2 on 2024-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100, verbose_name='Book Name')),
                ('SubjectName', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('LevelName', models.CharField(max_length=100, verbose_name='Level Name')),
                ('UploadFile', models.ImageField(max_length=500, null=True, upload_to='books', verbose_name='Upload File')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('ModifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
